### PR TITLE
Fix failing bundler on ruby 1.9.3

### PR DESCRIPTION
**Pull request by tbrisker**
see https://github.com/travis-ci/travis-ci/issues/5239

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Hmmm. Thanks for this @tbrisker but the build is still broken. =s

**Comment by tbrisker** [comment]
@plribeiro3000 looks like it is fixed now that #5 was merged

**Comment by plribeiro3000** [comment]
Yeap. Thanks!

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
