### PR TITLE
Remove gemnasium badge

### PR DESCRIPTION
**Pull request by micwoj92**
FYI it's also in different repos in this org
https://github.com/search?q=org%3Afog+gemnasium&type=code

### CODE REVIEW

**Comment by geemus** [comment]
@micwoj92 Thanks. Has gemnasium been discontinued or something? I hadn't heard or seen any related news, but see that link doesn't seem to be working any more.

**Comment by micwoj92** [comment]
I only know it has been acquired by gitlab
https://about.gitlab.com/press/releases/2018-01-30-gemnasium-acquisition.html

**Comment by micwoj92** [comment]
Here a bit more info from archived gemnasium blog
https://web.archive.org/web/20180130131642/https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/

**Comment by geemus** [comment]
Thanks!

**Review by geemus — APPROVED** [review]

**Pull request merged**
